### PR TITLE
Request.

### PR DESCRIPTION
**Pull request by dchoi3**
I don't know why mine has so much more code. It might be cause of the versions we got. The only thing that  I can see being a problem is the gradle home.

### CODE REVIEW

**Comment by cbfannin** [comment]
Looks like someone reintroduced the .idea directory that I added to the .gitignore file. .idea tracks files specific to our local IDE settings. So these will ALWAYS change and create conflicts. In order for us to ALL stop tracking them, you will have to remove the files from git on your local and commit the change.

**Comment by dchoi3** [comment]
Oh I see. If you go ahead and delete it and commit it then I will just pull it later

On Jan 27, 2017 3:15 PM, Charles <notifications@github.com> wrote:

Looks like someone reintroduced the .idea directory that I added to the .gitignore file. .idea tracks files specific to our local IDE settings. So these will ALWAYS change and create conflicts. In order for us to ALL stop tracking them, you will have to remove the files from git on your local and commit the change.

**Comment by jschmitt4** [comment]
Pull Approved

**Comment by jschmitt4** [comment]
This Pull Cannot be resolved in web editor. fix errors and request a pull again

**Comment by cbfannin** [comment]
Yeah, I'm trying to clean it up via CLI. Make sure you go into your local and remove the ".idea" directory from being tracked by git and commit that change. Otherwise this will happen again. After not tracking it the files will still exist on your local, just won't be passed around to one another.

**Pull request closed without merging**
